[package]
name = "astrid-sdk-macros"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
description = "Procedural macros for the Astrid OS System SDK"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
schemars = "0.8"
syn = { version = "2.0", features = ["full", "extra-traits"] }
