[package]
name = "astrid-capsule"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
description = "Core runtime management for User-Space Capsules in Astrid OS"

[dependencies]
astrid-core = { workspace = true }
astrid-vfs = { path = "../astrid-vfs" }
astrid-capabilities = { workspace = true }
astrid-events = { workspace = true }
astrid-storage = { workspace = true }
astrid-approval = { workspace = true, optional = true }
astrid-mcp = { workspace = true }
extism = { workspace = true }
uuid = { workspace = true }
tempfile = { workspace = true }
reqwest = { workspace = true }
blake3 = { workspace = true }
notify = "7"
serde = { workspace = true }
serde_json = { workspace = true }
toml = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
async-trait = { workspace = true }

[features]
default = ["approval"]
approval = ["astrid-approval"]
