[package]
name = "astrid-sdk"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
description = "System SDK for building User-Space Capsules for Astrid OS"

[dependencies]
astrid-sys = { path = "../astrid-sys" }
extism-pdk = "1.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
borsh = { version = "1.0.0", features = ["derive"] }
rmp-serde = "1.3.0"
thiserror = "1"

# The procedural macros that provide the magic #[astrid::capsule] DX
astrid-sdk-macros = { path = "../astrid-sdk-macros", optional = true }

[features]
derive = ["dep:astrid-sdk-macros"]
default = ["derive"]
